### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by Y0ngg4n** [lucasheld/uptime-kuma-api#19] opened 2023-02-22 12:12 UTC
It seems like this API has a memory leak.

![MemoryLeak](https://user-images.githubusercontent.com/30302975/220615855-ecc449e9-16b0-4e65-91ef-adce91127efd.png)

I have used this python program to test it:
```python
import threading
import time
from uptime_kuma_api import UptimeKumaApi

api = UptimeKumaApi("https://up.obco.pro")
print("Connected")
api.login("Yonggan", "PASSWORD")
print("Login")

def update():
    api.get_important_heartbeats()


def uptime_kuma_polling():
    while True:
        update()
        time.sleep(10)


if __name__ == '__main__':
    uptime_kuma_thread = threading.Thread(target=uptime_kuma_polling)
    uptime_kuma_thread.start()

```

The output was as expected:
```
mprof: Sampling memory every 0.1s
running new process
running as a Python program...
Connected
Login
```

So after the Login i am looping every 10 seconds to get the important heatbeats.

This is just a short example. I recognized it because my [Horus](https://github.com/Y0ngg4n/Horus) flask app that is using this API used 1,5GB memory after some hours.

**Comment by Y0ngg4n** [comment] 2023-02-22 13:42
![MemoryLeak](https://user-images.githubusercontent.com/30302975/220637066-f7b0f034-149d-4598-b091-112be8f5bed9.png)
Here another graph

**Comment by zimbres** [comment] 2023-02-24 22:16
Checking mine, 850M in use.

**Comment by Y0ngg4n** [comment] 2023-02-24 23:29
@zimbres thats way too much.

**Comment by lucasheld** [comment] 2023-02-26 11:33
Unfortunately I can not reproduce the problem. I have created a fresh Uptime Kuma 1.20.1 instance and added multiple monitors. Then I modified the monitors multiple times to fill the important heartbeats list. I used the latest uptime-kuma-api version (0.10.0).

```bash
docker run -it --rm -p 3001:3001 louislam/uptime-kuma:1.20.1
````

```python
import threading
import time
from uptime_kuma_api import UptimeKumaApi

api = UptimeKumaApi("http://127.0.0.1:3001")
print("Connected")
api.login("admin", "secret123")
print("Login")

def update():
    api.get_important_heartbeats()


def uptime_kuma_polling():
    while True:
        update()
        time.sleep(10)


if __name__ == '__main__':
    uptime_kuma_thread = threading.Thread(target=uptime_kuma_polling)
    uptime_kuma_thread.start()
```

![Figure_5](https://user-images.githubusercontent.com/44499529/221408003-e1c263db-b396-49c7-9f43-1e317a421dd6.png)

Can you please test with a fresh Uptime Kuma instance and provide a list of steps or include those steps in the python script on how to set up Uptime Kuma to reproduce the problem?

**Comment by lucasheld** [comment] 2023-02-26 11:42
Maybe it's related to https://github.com/louislam/uptime-kuma/issues/2820.

I have tested this with Ping monitors. Do you use a MongoDB monitor?  Then you can try to repeat your test with Uptime Kuma version 1.20.2.

**Comment by Y0ngg4n** [comment] 2023-02-26 12:55
@lucasheld so could you reproduce the issue?

**Comment by lucasheld** [comment] 2023-02-26 12:57
No, unfortunately not. Here is the current plot after even longer time.
![Figure_6](https://user-images.githubusercontent.com/44499529/221411776-9d932324-34dd-403d-9b51-b9921432f819.png)

**Comment by Y0ngg4n** [comment] 2023-02-26 12:58
@lucasheld Ok thats weird. Because in every app i used uptime-kuma-api i have this rising memory.

**Comment by Y0ngg4n** [comment] 2023-02-26 13:03
@lucasheld maybe it is a specific type of monitor i am using causing this?

**Comment by lucasheld** [comment] 2023-02-26 13:03
But you always used the same uptime Kuma instance right? Maybe it depends on the configuration. So we need a minimal reproducible example, including the configuration (monitors, ...).

**Comment by Y0ngg4n** [comment] 2023-02-26 13:03
@lucasheld yes it was always the same instance. I can create a new one like you with the docker container to find out what is causing this

**Comment by lucasheld** [comment] 2023-02-26 13:04
That would be great!

**Comment by Y0ngg4n** [comment] 2023-02-26 13:05
Give me some time to investigate which monitor is causing this problems.

**Comment by Y0ngg4n** [comment] 2023-02-26 14:17
@lucasheld  So after my testing i have found out, that adding a monitor to uptime kuma results in usually taking up 0,1 MiB more in the API application. 

Something weird was that it seems like if i pause or resume monitors the RAM usage increases by a constant value of 0,1 - 0,2 MiB? Idk
I had it that sometimes the memory gone up quite a while and then stopped again. I could not say that one specific monitor is causing problems. It seemed sometimes like only having this issue if i enabled ntfy notifications. But maybe it was just a correlation.

TCP Hosts did not increased memory usage at all (only when disabling them again i got 0,1 MIB more)

Generally Memory just always was going up. Even if i deleted monitors.

After i had enabled 23 Monitors with Notifications i had the constant rising again. So i think it is constantly rising, but just so slow that we can not see it and it gets faster the more monitors you add. Currently i have only achieved it to create the rising if i enable ntfy notifications.

I don´t know how exactly you have done the implementation, but maybe there is something piling up?
Some cache? maybe close the socket more often? I really don´t know. I have attached you the memgraph where i was enabling, adding, deleting, pausing monitors all time. i don´t think it will be helpfull to you because you don´t exactly know where i did what when, but you can see the memory is rising even if i delete all monitors.

![Figure_1](https://user-images.githubusercontent.com/30302975/221416056-a8b0848b-d948-48ef-9dfb-8f88894dd5b4.png)

**Comment by zimbres** [comment] 2023-02-26 14:43
I have 28 monitors um UK. Mostly Ping and one or two Http.
From this API I'm calling only get_monitors each minute or so.

Since I'm running on Kubernetes, I set a memory limit for the Pod, so, its killed for OOM from time to time.

![image](https://user-images.githubusercontent.com/29772043/221417475-1e785b98-5a29-47b6-b26f-7041f095e9cb.png)

**Comment by Y0ngg4n** [comment] 2023-02-26 16:12
@zimbres thats a good workaround for now! thank you for that!

**Comment by Y0ngg4n** [comment] 2023-03-05 09:22
@lucasheld did the infornation i provided help you?

**Comment by lucasheld** [comment] 2023-03-05 09:56
Sorry for the late feedback. Based on your information, I tried to reproduce the problem a few days ago by creating over 200 monitors with ansible-uptime-kuma. This has slightly increased the memory consumption, within an expected range, because the information about over 200 monitors is now also in memory. So I ran the system for a day with calling get_monitors every 5 seconds, but the memory consumption never increased. Then I edited and deleted some monitors, but the memory consumption didn't show any noticeable behavior there either.
Currently I don't have time to deal with this in more detail. At the end of the month I will take a closer look and run the system for a longer time.

**Comment by Y0ngg4n** [comment] 2023-03-05 10:22
@lucasheld maybe try different types of monitors too. So tcp and keyword monitors for example.

**Comment by lucasheld** [comment] 2023-03-05 10:40
The monitors were ping and http as described by @zimbres. But yes, I will test all this, also in combination with notifications and other elements.

**Comment by ZleFox** [comment] 2023-03-23 05:52
I have this issue with 6 monitors. 1 TCP and 5 HTTPS
In 3 days the slab unreclaimable will rise, eating up all the ram and the cpu will be in waiting 80% of the time. Uptime kuma would start sending lots of false positives as the server is barely usable. I had to restart the host to make it work again. In the slabstats the kmallock 2k and 4k were huge, which led me to look at memory leak. As I have recently upgraded the server to 22.04 prior to installing the uptime kuma stack it took me awhile to realize what is crashing the host. 
I can try with alpine image to see if there is any difference
Here is the memory slab unreclaimed (total server ram is 24G and at this point the waiting usage of the cpu starts to kick off rendering the host unusable) The drop point is server restart 
![image](https://user-images.githubusercontent.com/22940823/227114606-befb7830-4c8d-42f3-972a-dc65cd3ed6a5.png)

**Comment by lucasheld** [comment] 2023-03-25 19:06
@Y0ngg4n @zimbres 
I think I have fixed the issue. Some events were added to a list after they were received, without ever limiting the size of the list. I now handle the events in the same way as uptime kuma does ([example](https://github.com/louislam/uptime-kuma/blob/958354e4db31eb59e7f054fb6a236c5ad1b9045f/src/mixins/socket.js#L166)).

It would be very helpful if you could test this.
But note that I have changed the return values of the methods `get_heartbeats`, `get_important_heartbeats`, `avg_ping`, `uptime`, `get_heartbeat` and `cert_info`.

Uninstall the python module:
```shell
pip uninstall -y uptime-kuma-api
```

And install it again from the bugfix branch:
```shell
pip install git+https://github.com/lucasheld/uptime-kuma-api.git@bugfix/memory-leak
```

**Comment by Y0ngg4n** [comment] 2023-03-25 19:34
@lucasheld wow 🥳 great! Thank you for your work! I will check it the next days if it fixed the issue and will give you a feedback. 😊

**Comment by FliKites** [comment] 2023-04-03 15:06
> @lucasheld wow partying_face great! Thank you for your work! I will check it the next days if it fixed the issue and will give you a feedback. blush

Did you test this yet by chance?

**Comment by Y0ngg4n** [comment] 2023-04-04 08:48
> > @lucasheld wow partying_face great! Thank you for your work! I will check it the next days if it fixed the issue and will give you a feedback. blush
> 
> Did you test this yet by chance?

No sorry did not had time. Maybe @zimbres can you test it?

**Comment by zimbres** [comment] 2023-04-04 14:58
Im not able to test now, since my app relies on "active": true and this version is returning "active": 1, my app broken.

**Comment by lucasheld** [comment] 2023-04-04 15:44
> Im not able to test now, since my app relies on "active": true and this version is returning "active": 1, my app broken.

Thank you for reporting this. It is not supposed to be like this. I will fix it soon.

**Comment by zimbres** [comment] 2023-04-07 22:24
@lucasheld 

So far, running smoothly

![image](https://user-images.githubusercontent.com/29772043/230686165-a00fd502-9231-45d9-ab3d-87536e149428.png)

**Comment by zimbres** [comment] 2023-04-09 00:10
More than 2 days without the OOK

![image](https://user-images.githubusercontent.com/29772043/230747719-66c00f5d-9144-43de-a8dd-a6c65a9140cc.png)

**Comment by lucasheld** [comment] 2023-04-09 08:12
Thank you very much for testing.
Because of the breaking changes (changed return values of the methods `get_heartbeats`, `get_important_heartbeats`, `avg_ping`, `uptime`, `get_heartbeat` and `cert_info`) I have to release a new major version.
I need a few days to check if there are any other useful breaking changes that should be included in this version.

**Comment by Vinalti** [comment] 2023-04-27 23:41
Maybe you can make a branch for that version, and a PR from it, so we can review it, and maybe add other features to it, one by one.

**Closed** 2023-05-19 12:07 UTC

**Comment by lucasheld** [comment] 2023-05-26 09:50
It's included in release 1.0.1

**Comment by tigunia-martin** [comment] 2023-06-22 04:19
> It's included in release 1.0.1

Is there an easy way to tell the current installed version (docker)? I'm experiencing a major memory leak (in 3 weeks 6.6Gb of RAM) and wondering if somehow my docker file with image: medaziz11/uptimekuma_restapi pulled an old version.

**Comment by FliKites** [comment] 2023-06-22 04:23
@tigunia-martin What you can do is go inside the docker contianer and find the file(s) that were updated and see if those commits are included in the files in your contianer. 

docker exec -it <container-name> sh

Then when you are in navigate to the files and use cat to display the outputs

**Comment by tigunia-martin** [comment] 2023-06-22 04:55
Thanks @FliKites 
Looks like I have version 1.2.1. I'll open a new issue.

**Comment by lucasheld** [comment] 2023-06-22 07:55
@tigunia-martin 
MedAziz11/Uptime-Kuma-Web-API version 1.2.1 [uses uptime-kuma-api version 0.13.0](https://github.com/MedAziz11/Uptime-Kuma-Web-API/blob/v1.2.1/requirements.txt#L31). This version is affected by the memory leak.

**Comment by tigunia-martin** [comment] 2023-06-22 14:14
@lucasheld I apologize profusely. I was following issues, linked PRs, and discussions and somehow moved from the web-api repo to the api repo without realizing.

Of course, I will bring this back to the correct github issues so that we can hopefully get the web api wrapper updated to use the newer API

Again, sorry, and thank you.
